# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-20 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_loc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcatg', models.CharField(max_length=100)),
                ('mtitle', models.CharField(max_length=500)),
                ('mprice', models.FloatField(default=0.0)),
                ('mimg', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_qt', models.IntegerField(default=0)),
                ('pay', models.BooleanField(default=True)),
                ('d_time', models.DateTimeField(default=None)),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rname', models.CharField(max_length=500)),
                ('Rimg', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(default=0)),
                ('usrrating', models.FloatField(default=0.0)),
                ('review', models.TextField(max_length=1000)),
                ('catg', models.CharField(max_length=500)),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Core')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='m_rest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Rest'),
        ),
    ]
