# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-06 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
