# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-06 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.IntegerField(default=0),
        ),
    ]
